import Evented from 'dojo-core/Evented';
import global from 'dojo-core/global';
import { Handle } from 'dojo-core/interfaces';
import { createHandle } from 'dojo-core/lang';
import { RouterSource } from './interfaces';

/**
 * Provides browswer navigation via the `hashchange` event.
 */
export default class HashSource extends Evented implements RouterSource {
	protected _current: { hash: string; path: string };
	protected _handle: Handle;
	protected _prefix: string;
	protected _prefixPattern: RegExp;

	/**
	 * The current URL has (without the hash character).
	 */
	get currentPath(): string {
		return global.location.hash.replace('#', '');
	}

	/**
	 * The string prefix that should be added immediately after the hash character. This is useful
	 * for distinguishing between hash changes generated by a particular router vs those generated
	 * outside the routing system. Defaults to an exclamation point ("!").
	 */
	get prefix(): string {
		return this._prefix;
	}
	set prefix(prefix: string) {
		this._prefix = prefix || '';
		this._prefixPattern = new RegExp('^#?' + this._prefix, 'g');
	}

	constructor(prefix: string = '!') {
		if (!('location' in global) || !('addEventListener' in global)) {
			throw new Error('HashSource requires a browser.');
		}

		super();

		this.prefix = prefix;
		this._current = <any> {};

		this._registerEvents();
	}

	protected _emit(): void {
		this.emit({
			type: 'change',
			hash: this._current.hash,
			path: this._current.path
		});
	}

	protected _handleHashChange(event: HashChangeEvent): void {
		const url = event.newURL;
		const hash = url.slice(url.indexOf('#') + 1);
		const path = this._normalizePath(hash);

		if (path) {
			this._current.hash = hash;
			this._current.path = path;
			this._emit();
		}
	}

	protected _normalizePath(path: string): string {
		return this._prefixPattern.test(path) ? path.replace(this._prefixPattern, '') : null;
	}

	protected _registerEvents(): void {
		const handleHashChange = this._handleHashChange.bind(this);

		global.addEventListener('hashchange', handleHashChange);
		this._handle = createHandle(function () {
			global.removeEventListener('hashchange', handleHashChange);
		});
	}

	/**
	 * Disables the instance so that it no longer affects the browser state.
	 */
	destroy(): void {
		this._handle.destroy();
		this.go = function () {};
	}

	/**
	 * Sets the URL hash to the provided path. If no path is provided, then it is assumed
	 * assumed that the current hash is meant to be treated as the new path. In this case,
	 * a "change" event is emitted, with the expectation that the router can then pass control
	 * to the appropriate route.
	 */
	go(path: string): void {
		const normalized = (path.charAt(0) === '/') ? path : '/' + path;

		if (normalized !== this._current.path) {
			global.location.hash = this.prefix + normalized;
		}
	}
}
